
version: '3.7'
services:
  web:
    image: test:latest
    build: ./mainapp-ui/
    ports:
      - 3000:3000
    volumes:
      - '/app/node_modules'
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=isp_3lab_db
    restart: always
  server:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./:/app/
    ports:
      - 8000:8000

volumes:
  postgres_data:
    driver: local
