# Generated by Django 3.2 on 2021-04-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_blogpost_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Thread',
        ),
    ]
