# Generated by Django 3.2 on 2021-04-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_thread_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.board', verbose_name='Имя категории'),
        ),
    ]
