# Generated by Django 3.2 on 2021-05-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='related_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_related_board', to='mainapp.board', verbose_name='Имя борды'),
        ),
    ]
