# Generated by Django 3.2 on 2021-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_comment_related_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_blessed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
