# Generated by Django 3.2 on 2021-05-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_comment_related_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='related_board',
        ),
    ]
