# Generated by Django 3.2 on 2021-05-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_comment_related_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pub_date',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.AlterField(
            model_name='comment',
            name='related_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.thread', verbose_name='Имя треда'),
        ),
    ]
