# Generated by Django 3.2 on 2021-05-07 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_auto_20210506_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
