# Generated by Django 3.2 on 2021-05-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_thread_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='owner',
        ),
    ]
