# Generated by Django 3.2 on 2021-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_thread_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
