# Generated by Django 3.2 on 2021-05-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_thread_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='blog_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.board', verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
