# Generated by Django 3.2 on 2021-05-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210507_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_thread',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.thread', verbose_name='Имя треда'),
        ),
    ]
