# Generated by Django 3.2 on 2021-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_thread_compressed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
