# Generated by Django 3.2 on 2021-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_thread_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./'),
        ),
    ]
