[a]
classname = "A"
funcs = "None"

[a.attrs]
name = "name"
test = "test"

[a.supers]
classname = "B"
funcs = "None"

[a.supers.attrs]
test = "test"

[a.supers.supers]
classname = "C"
funcs = "None"

[a.supers.supers.attrs]
test = "test"
